local ASSET_ACCESSORY_TYPES = {
	[Enum.AvatarAssetType.Hat] = Enum.AccessoryType.Hat,
	[Enum.AvatarAssetType.HairAccessory] = Enum.AccessoryType.Hair,
	[Enum.AvatarAssetType.FaceAccessory] = Enum.AccessoryType.Face,
	[Enum.AvatarAssetType.NeckAccessory] = Enum.AccessoryType.Neck,
	[Enum.AvatarAssetType.ShoulderAccessory] = Enum.AccessoryType.Shoulder,
	[Enum.AvatarAssetType.FrontAccessory] = Enum.AccessoryType.Front,
	[Enum.AvatarAssetType.BackAccessory] = Enum.AccessoryType.Back,
	[Enum.AvatarAssetType.WaistAccessory] = Enum.AccessoryType.Waist,

	[Enum.AvatarAssetType.ShirtAccessory] = Enum.AccessoryType.Shirt,
	[Enum.AvatarAssetType.TShirtAccessory] = Enum.AccessoryType.TShirt,
	[Enum.AvatarAssetType.SweaterAccessory] = Enum.AccessoryType.Sweater,
	[Enum.AvatarAssetType.JacketAccessory] = Enum.AccessoryType.Jacket,
	[Enum.AvatarAssetType.PantsAccessory] = Enum.AccessoryType.Pants,
	[Enum.AvatarAssetType.DressSkirtAccessory] = Enum.AccessoryType.DressSkirt,
	[Enum.AvatarAssetType.ShortsAccessory] = Enum.AccessoryType.Shorts,
	[Enum.AvatarAssetType.LeftShoeAccessory] = Enum.AccessoryType.LeftShoe,
	[Enum.AvatarAssetType.RightShoeAccessory] = Enum.AccessoryType.RightShoe,

	[Enum.AvatarAssetType.EyelashAccessory] = Enum.AccessoryType.Eyelash,
	[Enum.AvatarAssetType.EyebrowAccessory] = Enum.AccessoryType.Eyebrow,
}

return ASSET_ACCESSORY_TYPES
